name: Release to CurseForge

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and upload
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: -p ${{ secrets.CURSEFORGE_PROJECT_ID }}
